/** @type {Array<{ id: string, name: string, location: string, matches: string, description: string, featured?: boolean }>} */
export const STADIUM_COVERAGE = [
  {
    id: 'metlife',
    name: 'MetLife Stadium',
    location: 'East Rutherford, NJ',
    matches: '8+ Matches',
    description: 'Host Of The FIFA 2026 Final',
  },
  {
    id: 'sofi',
    name: 'SoFi Stadium',
    location: 'Inglewood, CA',
    matches: '8 Matches',
    description: 'Premier Los Angeles Venue',
  },
  {
    id: 'att',
    name: 'AT&T Stadium',
    location: 'Arlington, TX',
    matches: '8 Matches',
    description: "Cowboys' Iconic Dallas Venue",
  },
  {
    id: 'hard-rock',
    name: 'Hard Rock Stadium',
    location: 'Miami Gardens, FL',
    matches: '7 Matches',
    description: "South Florida's Marquee Stadium",
    featured: true,
  },
  {
    id: 'mercedes-benz',
    name: 'Mercedes-Benz Stadium',
    location: 'Atlanta, GA',
    matches: '8 Matches',
    description: "Atlanta's Modern Football Landmark",
  },
  {
    id: 'nrg',
    name: 'NRG Stadium',
    location: 'Houston, TX',
    matches: '7 Matches',
    description: "Houston's Premier Match Venue",
  },
  {
    id: 'levis',
    name: "Levi's Stadium",
    location: 'Santa Clara, CA',
    matches: '6 Matches',
    description: "Bay Area's Flagship Stadium",
  },
  {
    id: 'arrowhead',
    name: 'Arrowhead Stadium',
    location: 'Kansas City, MO',
    matches: '6 Matches',
    description: 'Heart Of America Host Venue',
  },
  {
    id: 'lumen',
    name: 'Lumen Field',
    location: 'Seattle, WA',
    matches: '6 Matches',
    description: 'Pacific Northwest Host Venue',
  },
  {
    id: 'lincoln-financial',
    name: 'Lincoln Financial Field',
    location: 'Philadelphia, PA',
    matches: '6 Matches',
    description: "Philadelphia's Premier Stadium",
  },
  {
    id: 'bmo',
    name: 'BMO Field',
    location: 'Toronto, ON',
    matches: '6 Matches',
    description: "Canada's Top Football Venue",
  },
  {
    id: 'bc-place',
    name: 'BC Place',
    location: 'Vancouver, BC',
    matches: '7 Matches',
    description: "Vancouver's Iconic Indoor Venue",
  },
]
