import {
  Armchair,
  ArrowLeft,
  ArrowRight,
  Bath,
  CalendarCheck,
  Car,
  CarFront,
  Check,
  ChevronDown,
  Clock,
  GripVertical,
  Headset,
  Home,
  IdCard,
  Lightbulb,
  Luggage,
  Mail,
  MapPin,
  Maximize2,
  Menu,
  Phone,
  Plane,
  Quote,
  Route,
  Search,
  Settings,
  ShieldHalf,
  Snowflake,
  Sofa,
  Sparkles,
  Star,
  Tv,
  User,
  Users,
  Wine,
  X,
} from 'lucide-react'
import { FacebookIcon, TwitterIcon, YoutubeIcon } from './brandIcons.jsx'

/**
 * Central icon registry — add new icons here only.
 * Keys are kebab-case names used by <Icon name="..." />.
 */
export const ICON_MAP = {
  // Common / navigation
  home: Home,
  user: User,
  settings: Settings,
  search: Search,
  menu: Menu,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  check: Check,
  x: X,
  mail: Mail,
  phone: Phone,

  // Site UI (legacy Font Awesome names preserved)
  star: Star,
  envelope: Mail,
  'shield-halved': ShieldHalf,
  car: Car,
  'id-card': IdCard,
  plane: Plane,
  'quote-left': Quote,
  'chevron-down': ChevronDown,
  suitcase: Luggage,
  snowflake: Snowflake,
  couch: Sofa,
  chair: Armchair,
  'wine-glass': Wine,
  lightbulb: Lightbulb,
  tv: Tv,
  'grip-lines-vertical': GripVertical,
  expand: Maximize2,
  users: Users,
  restroom: Bath,
  clock: Clock,
  'location-dot': MapPin,
  headset: Headset,
  'id-badge': IdCard,
  'car-side': CarFront,
  'calendar-check': CalendarCheck,
  route: Route,
  'clean-fleet': Sparkles,

  // Brand / social
  'facebook-f': FacebookIcon,
  twitter: TwitterIcon,
  youtube: YoutubeIcon,
}

/** @typedef {keyof typeof ICON_MAP} IconName */
